### ISSUE TITLE
Spawning in of more then one bot kicks both.

### ISSUE THREAD

**Issue by Sonicmaster13** [pulviscriptor/agario-client#34]
Whenever you spawn in more then one bot per party mode, it disconnects both of them. I have tried to console.log to track the issue, but it literally just says "disconnected." I can try to provide more information if necessary. Also, YES i am providing the party key. That would just be stupid ;P

**Comment by pulviscriptor** [comment]
Probably agar disconnects you for connection flood. Try to add pause between connections.

**Comment by Sonicmaster13** [comment]
I have tried that, it still disconnects both. i could have one script running, then when i open another connecting to the same server, maybe 10 minuets later, it kicks both.

**Comment by pulviscriptor** [comment]
I can't reproduce. 
After disconnect, are you able to connect back to that party? I mean, maybe that is server restarting?
Or your clients stable getting disconnected after 10 minutes every time?

**Comment by Sonicmaster13** [comment]
Yes, i can reconnect. i have tried with many party modes, and all of them give the same issue. Only once does it work, then it kicks me every time after. Try doing it many times, maybe then you can reproduce the issue? I have the latest version, just updated 5 minuets ago and tried my API again, still no luck.

**Comment by pulviscriptor** [comment]
Okay, tomorrow i will write example that uses 4-5 connections and we will test. Now i need sleep.
If somebody have same issue, please report it here.

**Comment by Sonicmaster13** [comment]
Ok, i have really tried to get it to work, no matter what i do, it just won't. I bet others do have the same problem, we'll see. Thanks for helping, and see ya tomorrow.

**Comment by pulviscriptor** [comment]
So i did it now.
Do `npm update` and run `node ./node_modules/agario-client/examples/multiple.js`
Will it disconnect after 5-10 mins too? 
Now i'm definitely go to sleep.

**Comment by Sonicmaster13** [comment]
Ooookkkkkk... now it works... must be the way I was doing it... Thanks lemme implement this into my api.

**Comment by Sonicmaster13** [comment]
Ok now i get a stupid error:
    if(this.ws.readyState !== WebSocket.OPEN) {
                  ^
    TypeError: Cannot read property 'readyState' of undefined

**Comment by pulviscriptor** [comment]
Do you get that error inside lib?
If so, looks like you found some major bug.
Please provide code to reproduce this error.

**Comment by pulviscriptor** [comment]
I looked at lib and found one way to cause this crash.
```javascript
var AgarioClient = require('agario-client');
var client = new AgarioClient('worker');
client.moveTo(1,1);
```
Added this case to packet drop. 
Do `npm update` and if this fixes your problem, then your code trying to send data to agar before even calling `connect()`

**Comment by Sonicmaster13** [comment]
Ok yes that must be the probelem, now it says the spawn() and moveto() were called before connection, BUT their WAS CONNECTION made! it said right before that: Connecting to (ip) with key (key)...
then:
Connected to Server
then it emited the event: connected
but after that is said the moveto() was called before connection, so THAT CAN'T BE RIGHT
 
ps: yes that was in the lib.

**Comment by Sonicmaster13** [comment]
ps: i have moveTo() inside the on connect event in the api, so it should do that AFTER it connects..... Its also in the respawn one, again, way after it connects.....

**Comment by Sonicmaster13** [comment]
oh, lol, something else, now i get a new error saying:

 return client.balls[ball_id].name || 'unnamed';

TypeError: Cannot read property 'name' of undefined

**Comment by pulviscriptor** [comment]
Can you show me code that causes warning about "before connection"?

**Comment by Sonicmaster13** [comment]
Ok, i have fixed most of it, and it works now, i forgot to do bot.client.spawn, and bot.client.moveTo, i still had the old client.spawn(), etc, but now when i add Facebook key in it disconnects them all again :C And even i remove Facebook key from the old it does not make it work, so that was not the problem before.

**Comment by pulviscriptor** [comment]
Do `node ./node_modules/agario-client/examples/multiple.js` have same issue? 
I testing it with facebook key for about 30mins and i can't reproduce issue.
Find there line
```javascript
this.client.debug = 1;
```
and add 
```javascript
this.client.facebook_key = '...';
```
to set key

**Comment by Sonicmaster13** [comment]
I have done this, it still won't work

**Comment by Sonicmaster13** [comment]
It kicks the bots still

**Comment by Sonicmaster13** [comment]
function spawnBot(bot_id) {
    this.bot_id = bot_id;
    this.nickname = botNick;
    this.verbose = true;
    this.interval_id = 0;

    this.server = server_ip;
    this.server_key = party_key;

    this.client = new RSBotz(this.bot_id);
	this.client.facebook_key = "g2gDYQFtAAAAECb2+A7m+Nm4lazSdIs1YcBtAAAAUm8nkKW1ndFo65t9UdglcPOsyw8cZaCGIgJlnUJTt+9kHguZeTxoCUuLsXNQPHHOmwqdDoXGuXlexDgUX/9EL3iWHpfdoMdoT7n2U87PJ3EeBfc=";
    this.client.debug = 1;
}

**Comment by pulviscriptor** [comment]
But without facebook key it is works fine?
I must say that this is something agar server related and if it is, i can't do anything.

**Comment by Sonicmaster13** [comment]
yes, it works fine without FBkey.

**Comment by Sonicmaster13** [comment]
I don't know what the problem is, i have tried everything i can think of...

**Comment by Sonicmaster13** [comment]
Also, i have another probelem. Lets say under the attachEvents i created a function called split, and in it i said bot.client.split like so

    function split() {
        bot.client.split;
    }

Lets say i wanted to execute this above the entire script, not in the prototype, or any of that, above it. How would i do that? i have tried things like split(); ExampleBot.split(); ExampleBot.attachEvents.split(); and none of that works. Am i being stupid?

**Comment by pulviscriptor** [comment]
Oh wait, i used wrong key when i was testing.
With valid fb key i can not connect more than 1 bot. 
So looks like you just can't play more than 1 bot with one key.
But you said you was able to play for 5-10 mins. Not sure how this works. When i try connect second bot, they both got disconnects.

**Comment by Sonicmaster13** [comment]
Yes, that's what i always get. It kicks both when using a Facebook Key. And when did i say i got to play for 5-10 mins with the FB Key?

**Comment by Sonicmaster13** [comment]
PS: I am attempting now to create a second Facebook account, and see if i try it with 2 separate FBKeys if it will let me. As of now, it looks as if it will still kick them :C

**Comment by pulviscriptor** [comment]
Also, i have another problem.
I'm not sure what you mean but you use `bot.client.split;` but you need `bot.client.split();` to work.
If that not solves your problem, explain little more what you mean.

    when did i say i got to play for 5-10 mins with the FB Key
That was initial issue. Was that without keys? Is it solved now?

**Comment by Sonicmaster13** [comment]
The issue was that i was able to play as long as i wanted or needed without keys. The second i use the fb key is kicks bots. I never got to play 5-10 mins, let alone at all, with the fb-keys. And that was a typo, i do have the bot.client.split(); my question i show do i execute that function, being inside the prototype, outside of it.

**Comment by Sonicmaster13** [comment]
Oh, and no, its not solved yet... it still kicks the bots, even with 2 seperate FB-keys.

**Comment by Sonicmaster13** [comment]
Ok, my test succeded, then failed. I know what the probelem is now. And what a wierd probelem it is! I think i may be close to closing the issue... Let me run a few more tests. PS it is with agario, not with your script.

**Comment by pulviscriptor** [comment]
my question i show do i execute that function, being inside the prototype, outside of it.
If i correctly understand, i will show based on `multiple.js`
You can see `bots[bot_id] = new ExampleBot(bot_id);` there, so if you want to command "Charlie" to call `moveTo()` somewhere outside of prototype you can do `bots['Charlie'].client.moveTo(1,1)` from any place.

I will close this issue since "issue" is inside agar server related to fb keys.
If i wrongly answered your question, feel free to write.

**Comment by Sonicmaster13** [comment]
Ok thanks for all of your help, the issue is closed, i fixed it!

**Comment by Sonicmaster13** [comment]
WE* fixed it :D
